# Generated by Django 3.2.7 on 2021-09-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountjournal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountJournal',
        ),
    ]
